---
title: "NES-LTER Attune flow cytometer continuous data EDI package assembly"
author: "Joe Futrelle and Stace Beaulieu"
date: "January 2023"
output: html_notebook
---

Libraries used

```{r}
# two of the required packages are installed from GitHub
# library(remotes)
# remotes::install_github("EDIorg/EMLassemblyline")
# remotes::install_github("WHOIGit/ediutilities")

library(EMLassemblyline)
library(ediutilities)
library(here)
library(readr)
library(lubridate)
```

Read data table

```{r}
# in the example we expected to merge cruises

# data_table <- merge_csv_directory(here("data")) # example
# data_table$datetime <- ymd_hms(data_table$datetime)

# now we read in the provided local csv file
# data_table <- read_csv(here("data/Attune_EDI_Table_merged.csv"))
# moving data table into main folder to get make_eml to run
data_table <- read_csv(here("attune-transect-underway-continuous.csv"))

```

```{r}
# write the data file to a CSV
# note this was not needed because data provider merged cruises

# data_table_filename <- "data_table.csv"
# write_csv(data_table, here(data_table_filename), na = "NaN")


```

Read the Excel metadata template and generate text templates used by
EMLassemblyline

```{r}
excel_to_template(here("nes-lter-attune-transect-info"),
                  "attune-transect-underway-continuous",
                  rights = "CCBY")
```
Generate the package and insert the parent project node into the resulting EML

```{r}
# now using actual package ID
pkg_id <- "knb-lter-nes.17.2"

# Because EDI has a file upload limit of 500 MB and our tar files are larger,
# dummy tar files were created in order to run the make_eml.
# After the make_eml is run, the output EML file was manually
# edited to enter the actual tar file checksums and file sizes instead of the
# dummy checksums and file sizes.

# WARNING!!! - if the make_eml is rerun, the manually edited checksums and file
#              sizes in knb-lter-nes.17.1 will be overwritten.

make_eml(here(),
         dataset.title = "Abundance, biovolume, and biomass of Synechococcus and eukaryote pico- and nano- plankton from continuous underway flow cytometry during NES-LTER Transect cruises, ongoing since 2018",
         data.table = "attune-transect-underway-continuous.csv",
         data.table.description = "Data table with picoeuk and Syn cell, biovolume, and biomass concentration and time and position sampled",
         data.table.name = "attune-transect-underway-continuous",
         temporal.coverage = temporal_coverage(data_table$date_time_utc),
         geographic.description = "NES-LTER Transect",
         geographic.coordinates = geographic_coordinates(data_table$latitude,
                                                         data_table$longitude),
         maintenance.description = "ongoing",
         user.id = "NES",
         user.domain = "LTER",
         other.entity = c("Settings_configuration_history.csv",
                          "nes_lter_attune_fcs_20180131_EN608.tar.bz2",
                          "nes_lter_attune_fcs_20180404_AR28B.tar.bz2",
                          "nes_lter_attune_fcs_20180414_AR29.tar.bz2",
                          "nes_lter_attune_fcs_20180720_EN617.tar.bz2",
                          "nes_lter_attune_fcs_20181020_AR31A.tar.bz2",
                          "nes_lter_attune_fcs_20190201_EN627.tar.bz2",
                          "nes_lter_attune_fcs_20190414_AR34B.tar.bz2",
                          "nes_lter_attune_fcs_20190512_RB1904.tar.bz2",
                          "nes_lter_attune_fcs_20190705_TN368.tar.bz2",
                          "nes_lter_attune_fcs_20190820_EN644.tar.bz2",
                          "nes_lter_attune_fcs_20191005_AR39A.tar.bz2",
                          "nes_lter_attune_fcs_20200201_EN649.tar.bz2",
                          "nes_lter_attune_fcs_20200311_AR43.tar.bz2",
                          "nes_lter_attune_fcs_20200725_EN655.tar.bz2",
                          "nes_lter_attune_fcs_20201013_EN657.tar.bz2",
                          "nes_lter_attune_fcs_20210203_EN661.tar.bz2",
                          "nes_lter_attune_fcs_20210716_EN668.tar.bz2",
                          "nes_lter_attune_fcs_20211108_AR61B.tar.bz2",
                          "nes_lter_attune_fcs_20211117_AR62.tar.bz2",
                          "nes_lter_attune_fcs_20211126_AR63.tar.bz2",
                          "nes_lter_attune_fcs_20220216_AT46.tar.bz2"
         ),
         other.entity.description = c("Metadata for instrument settings configuration per cruise",
                                      "raw FCS datafiles from Cruise EN608",
                                      "raw FCS datafiles from Cruise AR28B",
                                      "raw FCS datafiles from Cruise AR29",
                                      "raw FCS datafiles from Cruise EN617",
                                      "raw FCS datafiles from Cruise AR31A",
                                      "raw FCS datafiles from Cruise EN627",
                                      "raw FCS datafiles from Cruise AR34B",
                                      "raw FCS datafiles from Cruise RB1904",
                                      "raw FCS datafiles from Cruise TN368",
                                      "raw FCS datafiles from Cruise EN644",
                                      "raw FCS datafiles from Cruise AR39A",
                                      "raw FCS datafiles from Cruise EN649",
                                      "raw FCS datafiles from Cruise AR43",
                                      "raw FCS datafiles from Cruise EN655",
                                      "raw FCS datafiles from Cruise EN657",
                                      "raw FCS datafiles from Cruise EN661",
                                      "raw FCS datafiles from Cruise EN668",
                                      "raw FCS datafiles from Cruise AR61B",
                                      "raw FCS datafiles from Cruise AR62",
                                      "raw FCS datafiles from Cruise AR63",
                                      "raw FCS datafiles from Cruise AT46"
         ),
         package.id = pkg_id)

project_insert(pkg_id,'parent_project_SPIROPA_OTZ_RAPID.xml')

issues()
```
